services:
  app:
    build: ./
    volumes:
      - .:/workdir
    ports:
      - 8000:8000
  
  db:
    image: mysql:8.3
    volumes:
      - ./save_app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306